# application.yml
spring:
  profiles:
    include: common
    active: dev
    group:
      local:
        - local
      dev:
        - dev
      prod:
        - prod

---
# 공통 설정
spring:
  config:
    activate:
      on-profile: common # local과 dev에서 공통으로 사용할 설정 값
  cloud:
    aws:
      credentials:
        accessKey: ${AWS_ACCESS_KEY}
        secretKey: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2
      stack:
        auto: false
      s3:
        bucket: ${AWS_BUCKET_NAME}
  jwt:
    secret: ${JWT_SECRET}

---
# 로컬 설정
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul

---
# 개발 서버 설정
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://${DEV_MYSQL_HOST}:${MYSQL_PORT}/${DEV_DATABASE_NAME}
    username: ${DEV_MYSQL_USERNAME}
    password: ${DEV_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
        jdbc:
          time_zone: Asia/Seoul

---
# 운영 서버 설정
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DATABASE_NAME}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
        jdbc:
          time_zone: Asia/Seoul