spring:
  profiles:
    include: common
    active: local
    group:
      local:
        - local
      test:
        - test
      dev:
        - dev
      prod:
        - prod
---
spring:
  config:
    activate:
      on-profile: common
    import: classpath:/application-s3.yaml, classpath:/application-jwt.yaml

